#cloud-config

users:
  - name: alpine
    plain_text_passwd: "alpine"
    lock_passwd: false
    doas:
      - "permit nopass alpine"

chpasswd:
  list:
    - root:root
  expire: false

ssh_pwauth: false
