#cloud-config

users:
  - name: alpine
    plain_text_passwd: "alpine"
    lock_passwd: false
    doas:
      - "permit nopass alpine"

chpasswd:
  list:
    - root:root
  expire: false

ssh_pwauth: false

packages:
  - curl
  - iptables

bootcmd:
  - modprobe br_netfilter
  - modprobe overlay
  - modprobe ip_tables

write_files:
  - path: /etc/modules-load.d/k3s.conf
    content: |
      br_netfilter
      overlay
      ip_tables
  - path: /etc/sysctl.d/k3s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1

runcmd:
  - sysctl --system
  - swapoff -a
  - sed -i '/ swap / d' /etc/fstab
